<?php $this->headTitle()->prepend($this->translate('about-us')); ?>

<p>
Suntem o echipă tînără, care vrea să aducă inovație în internetul din Moldova.
Ne propunem ca scop să ajutăm utilizatorii internetului să folosească resursele acestuia cît mai eficient.
Punem la dispoziție cele mai moderne instrumente care vă permit să vă promovați online.
De aceste servicii dumneavoastră beneficiați gratis, veniturile noastre sunt colectate din alte surse,
deasemenea legate cu acest site.
</p>

