<?php $this->headTitle()->prepend($this->translate('about-us')); ?>

<p>
We are a young team and we want to bring innovation in the Internet in Moldova.
We plan to help Internet users to use its resources more effectively.
We offer the most modern tools that allow you to promote yourself online.
All these services you get for free, our revenues are collected from other sources
also related to this site.
</p>

