<?php $this->headTitle()->prepend($this->translate('advertising')); ?>
<p>
    To place advertising on our website please contact us via the
    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'contact', 'action' => 'index'), 'default', true); ?>">contact form</a>.
    After that you will receive detailed information about prices, user statistics and other information of interest.
</p>
