<?php $this->headTitle()->prepend($this->translate('advertising')); ?>
<p>
    Pentru a plasa publicitatea pe site-ul nostru contactați-ne prin intermediul
    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'contact', 'action' => 'index'), 'default', true); ?>">formei de contact</a>.
    După aceasta ve-ți primi informații detaliate despre prețuri , statistica utilizatorilor și alte informații care vă interesează.
</p>