<?php $this->headTitle()->prepend($this->translate('advertising')); ?>
<p>
    Чтобы разместить рекламу на нашем сайте, пожалуйста, свяжитесь с нами через
    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'contact', 'action' => 'index'), 'default', true); ?>">контактную форму</a>.
    После этого вы получите подробную информацию о ценах, пользователей статистических данных и другой информации, представляющей интерес.
</p>
