<?php $this->headTitle()->prepend($this->translate('menu-help')); ?>
<p>
Welcome to the page where you can read more about the opportunities and resources that are available to you. Here you can get your questions answered by reading to the end this page, as well as accessing <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'contact', 'action' => 'index'), 'default', true); ?>">contact form</a> where you can ask us any questions if you have not found an answer from this page and you will be answered within 24 hours.
</p>
<p>
At present, our main service is to offer our website users a catalog of companies, businesses, various organizations and any activity which may be located anywhere in the country, both cities and villages as well. These companies can be found by two criteria: by location and by category. By finding the company's page you are interested in you can see all information about this company and description.
</p>
<p>
Also here you can find useful information such as weather information, currency converter, latest news. All this information is continually updated, so that they reflect all the latest changes.
</p>
<p>
<strong>For users who want to add a company, firm, organization or any type of activity:</strong><br />
All you need is to go to add page that can be found <a href="<?php echo $this->url(array('controller' => 'companies', 'action' => 'add'), 'default', true); ?>">here</a>. There you will find all fields that can be filled. To get a greater appreciation from users is welcome to complete as many fields, also upload images from the company, personnel, products and more. Then your page will be created with the information you have filled it, and this page will have the address depending on the name you typed, so automatically have a high visibility in search engines (Google, Yahoo, Bing). What does this mean? This means that users looking for your name in Google, Yahoo, Bing will be able to easily find your page on our site.
</p>
<p>
In addition each page have buttons to promote, so you can  promote your page on any social network where you are registered. Since your page will be unique across the Internet, you can send the address to your friends via email or skype or any other source of communication. These friends can use the buttons to promote, so their friends will come to your page and  in turn the last will access the page and so on. So you can create a whole network around your page using the latest technologies.
</p>







