<?php $this->headTitle()->prepend($this->translate('menu-help')); ?>
<p>
Bine ați venit pe pagina, unde puteți să vă informați despre posibilitățile și resursele care sunt puse la dispoziția dumneavoastră. Aici puteți primi răspuns la întrebările care vă interesează atît citind pînă la capăt această pagină , cît și accesînd <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'contact', 'action' => 'index'), 'default', true); ?>">forma de contact</a> unde puteți să ne adresați orice întrebare în cazul în care nu ați găsit răspuns din acestă pagină și veți primi răspuns în decurs de 24 ore.
</p>
<p>
La moment, principalul nostru serviciu este de a propune utilizatorilor site-ului nostru un catalog de companii, firme, diferite organizații și orice tip de activitate care se poate afla în orice localitate a țării , atît orașe cît și sate. Aceste companii pot fi găsite dupa două criterii: după localitate și după domeniu de activitate. Găsind pagina companiei care vă interesează puteți vedea toată informația despre această companie și descriere.
</p>
<p>
Deasemenea aici puteți găsi informații utile cum ar fi datele meteo , cursul valutar, convertor valutar, ultimele noutăți. Toate aceste informații sunt actualizate permanent, așa încît ele reprezintă toate modificările de ultimă oră.
</p>
<p>
<strong>Pentru utilizatorii care doresc să adauge o companie, firmă, organizație sau orice tip de activitate:</strong><br />
Tot de ce aveți nevoie este să mergeți la pagina de adăugare care poate fi accesată <a href="<?php echo $this->url(array('controller' => 'companies', 'action' => 'add'), 'default', true); ?>">aici</a>. Acolo ve-ți găsi toate cîmpurile care pot fi completate. Pentru a beneficia de o apreciere mai mare din partea utilizatorilor este binevenit să completați cît mai multe cîmpuri, deasemena puteți încărca imagini din companie, personal, produse și altele. După aceasta pagina dumeavoastră va fi creată cu informația care ați completat-o și această pagina va avea adresa în dependență de denumirea pe care ați introdus-o, astfel automat dispuneți de o vizibilitate mare in motoarele de căutare (Google, Yahoo, Bing). Ce înseamnă aceasta? Aceasta înseamnă că utilizatorii căutînd denumirea dumeavoastră în Google, Yahoo, Bing o să vă poată ușor găsi pagina dumneavoastră pe site-ul nostru.
</p>
<p>
Pe lîngă aceasta pe fiecare pagină stau butoanele de promovare a paginii astfel puteți singuri să vă promovați pagina pe orice rețea socială unde sînteți inregistrat. Deoarece pagina dumneavoastră o sa fie unică în toată rețeaua internet, dumneavostra puteți să o trimiteți prietenilor prin intermediul email-ului sau skype sau orice altă sursă de comunicare. Acești prieteni pot folosi butoanele de promovare , astfel între prietenii lor va aparea pagina dumneavoastră, la rîndul lor acesti prieteni vor accesa și tot așa. Astfel puteti crea o rețea întreagă în jurul paginii dumneavoastră utilizînd tehnologiile de ultimă oră.
</p>