<?php $this->headTitle()->prepend($this->translate('menu-services')); ?>
<p>
Welcome to the page where are all the services we propose on our site so far.
</p>
<p>
Because we constantly work on adding new services and improving existing ones, this page will be regularly updated.
</p>
<p>
At the moment our main service is to collect and present a catalog of companies, businesses, various organizations and any other activity that may be located throughout the country. Thus, all users can view and search the catalog, but details about how you can add the company and the benefits, you can find the <a href="<?php echo $this->url(array('page' => 'help'), 'static-content', true); ?>">help page</a>.
</p>
<p>
On our site you can see information about the weather data for the current day and following days, the exchange rate for the current day and for most major currencies, currency converter which allows to quickly convert any currency into any currency, just enter amount, as well as the latest news.
</p>
<p>
Description of other services will be updated.
</p>




