<?php $this->headTitle()->prepend($this->translate('menu-services')); ?>
<p>
Bine ați venit pe pagina unde sunt prezentate toate serviciile pe care le propune site-ul nostru pînă la acest moment.
</p>
<p>
Deoarece noi permanent lucram la adăugarea serviciilor noi și la îmbunătățirea celor existente, această pagină va fi permanent actualizată.
</p>
<p>
La moment principalul nostru serviciu este de a colecta și prezenta un catalog de companii, firme, diferite organizații și orice alt tip de activitate care se poate afla pe întreg teritoriul țării. Astfel toți utilizatorii pot vedea și căuta în catalog , dar detalii despre felul cum puteți adăuga companie și care sunt beneficiile, puteți găsi pe <a href="<?php echo $this->url(array('page' => 'help'), 'static-content', true); ?>">pagina de ajutor</a>.
</p>
<p>
Pe site-ul nostru mai puteți vedea informații despre datele meteo pentru ziua curentă și următoarele zile, cursul valutar pentru ziua curentă și pentru cele mai importante valute, convertor valutar care permite de a transforma rapid orice valută în orice valută, este necesar doar să introduceți suma, cît și noutățile de ultimă oră.
</p>
<p>
Descrierea celorlalte servicii va fi actualizată permanent.
</p>
