<?php $this->headTitle()->prepend($this->translate('terms-conditions')); ?>
<p>
Conţinutul, design-ul, informaţiile  şi orice materiale legate de prezentul site sunt protejate de drepturile de autor.
</p>
<p>
Copierea, redistribuirea, folosirea sau publicarea oricăror din aceste informaţii sau parte din site, cu excepția cazului în care dețineți permisiunea în scris din partea deținătorilor acestui site,  este strict interzis.
</p>
<p>
Această pagină va fi actualizată , deaceea vă rugăm să fiți la curent cu ultimele modificări în condițiile pe care le punem la dispoziția dumneavoastră.
</p>