<?php $this->headTitle()->prepend($this->translate('terms-conditions')); ?>
<p>
The content, design, information and any materials related to this site are protected by copyright.
</p>
<p>
Copying, redistribution, use or disclosure of this information or any part of the site,unless you have written permission from the owners of this site is strictly prohibited.
</p>
<p>
This page will be updated, so please stay current with the latest changes in conditions that we put at your disposal.
</p>