<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title></title>
                <script type="text/javascript" src="js/ext_lib/ext/adapter/jquery/jquery-1.3.2.min.js"></script>
                <script type="text/javascript" src="js/ext_lib/ext/adapter/jquery/ext-jquery-adapter-debug.js"></script>
                <script type="text/javascript" src="js/ext_lib/ext/ext-all-debug.js"></script>

                <script type="text/javascript" src="js/ext_lib/TabCloseMenu.js"></script>
                <script type="text/javascript" src="js/ext_lib/Ext.ux.grid.RowActions.js"></script>
                <script type="text/javascript" src="js/ext_lib/docs.js"></script>
                <link href="js/ext_lib/ext/resources/css/ext-all.css" media="screen" rel="stylesheet" type="text/css" />
                <link href="css/ext/docs.css" media="screen" rel="stylesheet" type="text/css" />
                <link href="css/ext/plugins/Ext.ux.grid.RowActions.css" media="screen" rel="stylesheet" type="text/css" />
                <link href="css/ext/style.css" media="screen" rel="stylesheet" type="text/css" />
                <link href="css/ext/admin.css" media="screen" rel="stylesheet" type="text/css" />
        </head>
	<body scroll="no" id="docs">
            <div id="loading-mask" style=""></div>
            <div id="loading"> 
                <div class="loading-indicator"><img src="/images/ext/extanim32.gif" width="32" height="32" style="margin-right:8px;" align="absmiddle"/>Loading...</div>
            </div>

            <script type="text/javascript">
                Docs.classData = <?php print $this->menu;?>
            </script>

            <div id="header">
            <div class="api-title">Moldova - Admin Zona</div>
            </div>

            <div id="classes"></div>

            <div id="main"></div>
        </body>
</html>