
<!--
This is a minified version of the ThemeForest-Theme "Grape - Professional & Flexible Admin Template".
Author: Simon Stamm (Stammi)

Note: If you buy my theme on ThemeForest, you will receive the non-minified and commented/documentated version!
This is a minified version of my theme to prevent stealing.
-->

<!--[if lt IE 7]>
<html class="no-js ie6 oldie" lang=en><![endif]--> <!--[if IE 7]>
<html class="no-js ie7 oldie" lang=en><![endif]--> <!--[if IE 8]>
<html class="no-js ie8 oldie" lang=en><![endif]--> <!--[if gt IE 8]><!-->
<html class=no-js lang=en> <!--<![endif]-->
<!-- Mirrored from themes.stammtec.de/grape/login.html by HTTrack Website Copier/3.x [XR&CO'2010], Mon, 15 Aug 2011 04:44:17 GMT -->
<head> 
    <meta charset=utf-8>
    <link rel=dns-prefetch href="http://fonts.googleapis.com/">
    <meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
    <title>Login :: Grape - Professional &amp; Flexible Admin Template</title> 
    <link href="favicon.ico" rel="shortcut icon"/>
    <meta name=description content="">
    <meta name=author content="">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <link rel=stylesheet href='/css/administration.css'>
    <link href="http://fonts.googleapis.com/css?family=PT+Sans" rel=stylesheet type="text/css">
    <script src="/js/libs/modernizr-2.0.6.min.js"></script>
</head>
<body class=special-page>

        <?php echo $this->layout()->content ?>
        
<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.form.js"></script>
<script src="/js/administration_custom.js"></script>
<script>window.jQuery || document.write('<script src="/js/libs/jquery-1.6.2.min.js"><\/script>');</script>
<script defer src='/js/administration.js'></script>
<!--[if lt IE 7 ]>
<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
<script>window.attachEvent("onload", function() {
    CFInstall.check({mode:"overlay"})
});</script><![endif]--> </body>
<!-- Mirrored from themes.stammtec.de/grape/login.html by HTTrack Website Copier/3.x [XR&CO'2010], Mon, 15 Aug 2011 04:44:17 GMT -->
</html>