    <script>
        (function()
        {
            var winMaxHeight	= 300;
            var winMaxWidth	= 400;
            var windowActive	= false;
            var delWinMaxHeight	= 120;
            var delWinMaxWidth	= 280;
            var perPage         = <?php echo $this->perPage; ?>;

            var categoryStore = new Ext.data.JsonStore({
                url: 'admin/companies/get-categories',
                fields: ['category_id', 'name_en_US', 'name_ro_MD', 'name_ru_RU'],
                root: "items",
                id: 'id',
                totalProperty: 'total'
            });
            categoryStore.load();

            var categoryGrid = new Ext.grid.GridPanel({
                store: categoryStore,
                loadMask: true,
                columns: [
                    {header: "ID",  dataIndex: 'category_id', hideable: false, hidden: true},
                    {header: "Name EN", dataIndex: 'name_en_US'},
                    {header: "Name RO", dataIndex: 'name_ro_MD'},
                    {header: "Name RU", dataIndex: 'name_ru_RU'}
                ],
                viewConfig: {
                    autoFill: true,
                    forceFit: true
                },
                listeners: {
                    celldblclick: function() {
                            editCat();
                    }
                },
                bbar: new Ext.PagingToolbar({
			pageSize: perPage,
			store: categoryStore
		})
            });

            //edit window
            var categoryForm = new Ext.form.FormPanel ({
		id: 'category-form',
		baseCls: 'x-plain',
		bodyStyle: 'padding: 10px;',
		frame: true,
		labelWidth: 120,
		waitMsgTarget: true,
		monitorValid: true,
		items: [{
			xtype: 'textfield',
			fieldLabel: 'Name EN',
			name: 'name_en_US',
			id: 'name-en',
                        allowBlank: false,
			anchor: '90%'
		},{
			xtype: 'textfield',
			fieldLabel: 'Name RO',
			name: 'name_ro_MD',
			id: 'name-ro',
                        allowBlank: false,
			anchor: '90%'
		},{
			xtype: 'textfield',
			fieldLabel: 'Name RU',
			name: 'name_ru_RU',
			id: 'name-ru',
                        allowBlank: false,
			anchor: '90%'
		},{
			xtype: 'hidden',
			id: 'category-id',
			name: 'category_id'
		}]
            });

            var editWindow = new Ext.Window ({
		id: 'category-window',
		iconCls: 'edit-window',
		title: 'Edit Category',
		border: true,
		width: winMaxWidth,
		height: winMaxHeight,
		minWidth: winMaxWidth,
		minHeight: winMaxHeight,
		layout: 'form',
		plain: true,
		bodyStyle: 'padding: 10px;',
		modal: true,
		closeAction: 'hide',
		items: [categoryForm],
		listeners: {
			resize: function () {
				if (windowActive) {
					if (editWindow.getSize().height > winMaxHeight) {
						editWindow.setSize(editWindow.getSize().width, winMaxHeight);
					}
				}
			},
			activate: function () {
				windowActive = true;
			},
			hide: {
				fn : function(){
					windowActive = false;
				}
			}
		}
            });

            var buttonSubmit = categoryForm.addButton ({
                text: 'Save',
                type: 'submit',
                cls: 'x-btn-text-icon',
                icon: 'images/icons/accept.png',
                timeout: 10,
                formBind: true,
                handler: function() {
                    categoryForm.getForm().submit ({
                            timeout: 30000,
                            success: function(form,action) {
                                    editWindow.hide();
                                    categoryStore.load();
                                    UI.notify("Success", action.result.message);
                            },
                            failure: function(form,action) {
                                    Ext.Msg.alert("Warning", action.result.message);
                            },
                            url: 'admin/companies/add-edit-category', 
                            waitMsg: 'Saving...'
                    });
                }
            });

            var buttonCancel = categoryForm.addButton ({
                text: 'Cancel',
                cls: 'x-btn-text-icon',
                icon: 'images/icons/cancel.png',
                handler: function() {
                    editWindow.hide();
                }
            });

            //delete window
            var deletePanel = new Ext.form.FormPanel ({
                    name: 'delete-form',
                    baseCls: 'x-plain',
                    bodyStyle: 'padding: 10px;',
                    waitMsgTarget: true,
                    frame: true,
                    items: [{
                            xtype: 'hidden',
                            name: 'ids'
                    }, {
                            xtype: 'label',
                            text: 'Are you sure you want to delete category?'
                    }]
            })

            var deleteWindow = new Ext.Window ({
                    id: 'delete-window',
                    iconCls: 'delete-window',
                    title: 'Delete category',
                    border: true,
                    width: delWinMaxWidth,
                    height: delWinMaxHeight,
                    minWidth: delWinMaxWidth,
                    minHeight: delWinMaxHeight,
                    resizable: false,
                    layout: 'form',
                    plain: true,
                    bodyStyle: 'padding: 10px;',
                    buttonAlign: 'center',
                    modal: true,
                    closeAction: 'hide',
                    items: [ deletePanel ]
            });

            var submitDeleteBtn = deletePanel.addButton ({
                    text: 'Delete',
                    type: 'submit',
                    timeout: 10,
                    cls: 'x-btn-text-icon',
                    icon: 'images/icons/accept.png',
                    handler: function() {
                            deletePanel.getForm().submit ({
                                    timeout: 30000,
                                    success: function(form,action) {
                                            deleteWindow.hide();
                                            categoryStore.load();
                                            UI.notify("Success", action.result.message);
                                    },
                                    failure: function(form,action) {
                                            Ext.Msg.alert("Warning", action.result.message);
                                    },
                                    url: 'admin/companies/delete-category',
                                    waitMsg: 'Deleting...'
                            });
                    }
            });

            var cancelDeleteBtn = deletePanel.addButton ({
                    text: 'Cancel',
                    cls: 'x-btn-text-icon',
                    icon: 'images/icons/cancel.png',
                    handler: function() {
                            deleteWindow.hide();
                    }
            });

            // buttons and handlers

            var editCat = function() {
                var rec = categoryGrid.getSelectionModel().getSelected();
                editWindow.show();
                categoryForm.getForm().loadRecord(rec);
            };

            var addCat = function() {
                editWindow.show();
                categoryForm.getForm().reset();
                Ext.getCmp('category-id').setValue('0');
            };

            var deleteCat = function() {
                var sm = categoryGrid.getSelectionModel();
		var selectedRole = sm.getSelections();
		var count = sm.getCount();

		var a = [];
		for(var i = 0; i < count; i++){
			a.push(selectedRole[i].data.category_id);
		}

		deleteWindow.show();
		deletePanel.getForm().findField('ids').setValue(a.toString());
            };

            var editBtn = new Ext.Toolbar.Button({
                cls: 'x-btn-text-icon',
                icon: 'images/icons/application_edit.png',
                text: 'Edit Category',
                handler: editCat,
                disabled: true
            });

            var addBtn = new Ext.Toolbar.Button({
                cls: 'x-btn-text-icon',
                icon: 'images/icons/add.png',
                text: 'Add Category',
                handler: addCat
            });

            var deleteBtn = new Ext.Toolbar.Button({
                cls: 'x-btn-text-icon',
                icon: 'images/icons/cancel.png',
                text: 'Delete Category',
                handler: deleteCat,
                disabled: true
            });

            categoryGrid.getSelectionModel().on('selectionchange', function() {
                    editBtn.setDisabled(this.selections.length != 1);
                    deleteBtn.setDisabled(this.selections.length == 0);
                    return true;
            });

            var main_panel = new Ext.Panel({
                layout: 'fit',
                frame: false,
                border: false,
                items: [categoryGrid],
                tbar: new Ext.Toolbar({
                    items: [addBtn,'-',editBtn,'-',deleteBtn]
                })
            });
            
            UI.activeTab.add(main_panel);
            UI.activeTab.setTitle('Categories');

            UI.activeTab.doLayout();
            UI.statusbar.clearStatus();
        }) ();
    </script>
</body>